### ISSUE TITLE
as_GPS problem

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-async#102]
I've just been trying out as_GPS.  I have a problem with giving a command to my adafruit ultimate GPS and I'm running the code on a rpi picoW, but I don't think the particular GPS or the board is the problem as the issue is a python error message  :
**TypeError: string argument without an encoding.**

This occurs in the following code:
```
import uasyncio as asyncio
from as_rwGPS import GPS
from machine import UART

uart = UART(0, 9600)
sreader = asyncio.StreamReader(uart)  # Create a StreamReader
swriter = asyncio.StreamWriter(uart, {})
gps = GPS(sreader, swriter)  # Instantiate GPS

async def test():
    print('waiting for GPS data')
    await gps.data_received(position=True, altitude=True)
    await gps.update_interval(2000)  # Reduce message rate
    for _ in range(10):
        print(gps.latitude(), gps.longitude(), gps.altitude)
        await asyncio.sleep(2)

asyncio.run(test())
```
The problem is in the line  ' await gps.update_interval(2000)  # Reduce message rate'

and this links to line 78 in as_reGPS.py where the error occurs:
sentence = bytearray('$PMTK220,{:d}*00\r\n'.format(ms))

In case it was an older version of mp for the picoW causing the error I installed the latest nightly build, but the error still remains.    

Thanks for any help on this.

**Comment by peterhinch** [comment]
This is puzzling. I have done a lot of testing on the Pico UART and am confident that with recent firmware it works well. I would check for electrical problems, notably drooping supply voltage to the GPS or bad ground connections.

**Comment by peterhinch** [comment]
I will attempt to replicate this, hopefully later today.

The tracebacks you posted suggest communication problems on the serial interface. This is puzzling, firstly because the way GPS uses the interface is very basic: no flow control, communications usually unidirectional, data newline terminated. It is also puzzling because I and others have tested the Pico serial ports under demanding conditions. These are the reasons why I suspect an electrical issue.

The `TypeError: string argument without an encoding` is a bug. Evidently something in the MP runtime has changed since I tested this. I will push an update. For a quick fix to `update_interval` please change  "as_rwGPS.py", line 78 to read
```python
sentence = bytearray('$PMTK220,{:d}*00\r\n'.format(ms).encode())
```
This bug will affect other operations such as `baudrate`.

**Comment by peterhinch** [comment]
The above code sample runs indefinitely (> 1 hour). I will update the docs for RP2.
