### ISSUE TITLE
Double click not working

### ISSUE THREAD

**Issue by Lisa999** [peterhinch/micropython-async#24]
Using your latest aswitch/pushbutton functions press/release/double/long.
Using constructor `pb = Pushbutton(pbpin,suppress=True)`
The press, release and long functions are working, however the double function not regardless how fast i press the second time...
The async loop is busy, might that be a reason it doesn't seem to notice the second click? The double click is noticed as a single click.

You do know that the pushbutton function is checking the state of the pin every 50ms and if the pin has changed from 0 to 1 to 0 in that 50ms, you will not notice it?

Instead of poll, is Pin.irq an option? That will also release the pressure on the loop, since it won't check the pins anymore until the pins are actually pressed...

**Comment by peterhinch** [comment]
I can't replicate this. On the Pyboard I ran
```import astests
astests.test_btn(True)
```
With a button between X1 and gnd a double click causes the yellow LED to flash.
Have you got a coroutine which is hogging the CPU?

Regarding your observation about very short presses this is true, but it seems rather theoretical. I've never managed to push a button that briefly. In any event debouncing a switch requires at least 50ms. Some claim [it should be longer](http://www.ganssle.com/debouncing.htm).

Using an IRQ is a valid approach. Feel free to do so but the purpose of this library is to offer a **uasyncio** solution.

**Comment by Lisa999** [comment]
I have build a mix of async and isr routines, where the buttoncheck is waiting (checking every 50ms) for a flag set by the ISR's, therfor it wil not go into the loop until a button is actually rising or falling. State or pinvalue is no longer required, the rising/falling flank (falling=press, rising=release) tells the tale...

**Comment by peterhinch** [comment]
The quickest I can press a button is about 5Hz, a 200ms interval. Running functions which hog the processor for anything like that time is not good programming practice if you're running a cooperative scheduler in a system requiring millisecond-level responses. I would start to worry if a function took longer than 20ms; in some systems the threshold is less than that. The solution is to launch a coroutine and to ensure it yields regularly.

If for some reason you have routines which must hog the CPU for long periods, a cooperative scheduler is not appropriate for your system. Interrupts and/or a pre-emptive scheduler may be your best recourse.

**Comment by Lisa999** [comment]
The problem scenario:
- Pushbutton is pressed and released for the **first** time
- Press function coro is called due to the code in buttoncheck: `await asyncio.sleep_ms(Pushbutton.debounce_ms)`. This happens ALWAYS regardless how idle the soc is, because the press coro is scheduled just before the sleep.
- Press function stores value on queue, which takes more then a second
- The release of the button is missed (press function takes to long)
- The **second** press and release is also missed 

Disabling the press function and using the suppress parameter, press value is not used anyhow, makes it work again...

Maybe add a warning specific for the press function? This function **MUST** be _VERY_ quick, or the pushbutton function will miss the release and other button actions...
Better is not to use it at all and use the release function only together with the suppress parameter.

**Comment by peterhinch** [comment]
In designing asynchronous applications I use callbacks sparingly: where possible I launch a coroutine rather than a callback. When I do use callbacks I aim for them to be **very** quick. They might set an event or update bound data. They might launch coros or trigger a millisecond timer. On the Pyboard their runtimes might be on the order of 1ms. I treat callbacks rather like interrupt service routines for precisely the reasons you have identified.

The hard work is done by coroutines which yield regularly.

It is just a fact of life that, if you need millisecond-level response times you have to think hard about blocking times at every point in the code path. The switch and pushbutton classes are intended for that type of application.

I'll add a warning to that effect - thank you for the suggestion.

An interrupt driven Pushbutton class would be an interesting project which would circumvent these problems. Alas I'm too committed with other things even to asses its feasibility. It might be hard to make cross-platform, but that's just an off-the-top-of-my-head guess.

**Comment by peterhinch** [comment]
Note now added to PRIMITIVES.md.
